services:
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_network
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  dorachat-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/dorachat:latest
    container_name: dorachat_backend
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - redis_network
    env_file:
      - .env
    restart: always

volumes:
  redis_data:

networks:
  redis_network:
