name: Docker API DoraChat Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-push-dorachat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push dorachat image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: | 
        docker compose -f docker-compose.yml build dorachat-backend
        docker compose -f docker-compose.yml push dorachat-backend

  deploy-dorachat:
    needs: build-push-dorachat
    runs-on: ubuntu-latest

    steps:
    - name: Deploy dorachat image
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/dorachat:latest
          docker-compose -f docker-compose.yml up -d dorachat-backend
