name: Docker API DoraChat Image CI/CD

on:
  push:
    branches: [ "feature/ci-cd-setup" ]
  pull_request:
    branches: [ "feature/ci-cd-setup" ]

jobs:
  build-push-dorachat-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push dorachat backend image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: | 
        docker compose -f docker-compose.yml build dorachat-backend
        docker compose -f docker-compose.yml push dorachat-backend
